// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertLesson implements pgx.CopyFromSource.
type iteratorForInsertLesson struct {
	rows                 []InsertLessonParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLesson) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLesson) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SnapshotID,
		r.rows[0].GroupID,
		r.rows[0].OccursOn,
		r.rows[0].StartsAt,
		r.rows[0].EndsAt,
		r.rows[0].Subject,
		r.rows[0].Kind,
		r.rows[0].Teacher,
		r.rows[0].Building,
		r.rows[0].Room,
		r.rows[0].WeekType,
		r.rows[0].SourceUrl,
	}, nil
}

func (r iteratorForInsertLesson) Err() error {
	return nil
}

func (q *Queries) InsertLesson(ctx context.Context, arg []InsertLessonParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lesson"}, []string{"id", "snapshot_id", "group_id", "occurs_on", "starts_at", "ends_at", "subject", "kind", "teacher", "building", "room", "week_type", "source_url"}, &iteratorForInsertLesson{rows: arg})
}
