// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthzAudit struct {
	ID          uuid.UUID
	PrincipalID pgtype.UUID
	Action      string
	ObjectType  string
	ObjectID    string
	Allowed     bool
	RecordedAt  pgtype.Timestamptz
}

type HintOutbox struct {
	ID          uuid.UUID
	Collection  string
	ScopeID     string
	Lsn         int64
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Institute struct {
	ID   uuid.UUID
	Code string
	Name string
}

type Lesson struct {
	ID         uuid.UUID
	SnapshotID uuid.UUID
	GroupID    uuid.UUID
	OccursOn   pgtype.Date
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
	Subject    string
	Kind       string
	Teacher    string
	Building   string
	Room       string
	WeekType   string
	SourceUrl  string
}

type LessonChange struct {
	ID         uuid.UUID
	GroupCode  string
	AuthorID   uuid.UUID
	Kind       string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

type LoroDoc struct {
	DocID           string
	LatestSnapshot  []byte
	SnapshotVersion int64
	UpdatedAt       pgtype.Timestamptz
}

type MiniappRelease struct {
	AppID        string
	Version      string
	BundleSha256 string
	Signature    string
	Manifest     []byte
	Status       string
	CreatedAt    pgtype.Timestamptz
}

type Principal struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

type PushReceipt struct {
	ReplicaID  uuid.UUID
	ClientSeq  int64
	Collection string
	ScopeID    string
	Lsn        int64
}

type ScheduleSnapshot struct {
	ID            uuid.UUID
	GroupID       uuid.UUID
	DocumentID    uuid.UUID
	ParserVersion string
	ContentSha256 string
	LessonCount   int32
	ValidFrom     pgtype.Timestamptz
	SupersededAt  pgtype.Timestamptz
}

type Session struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	SecretHash  []byte
	ExpiresAt   pgtype.Timestamptz
}

type SourceDocument struct {
	ID            uuid.UUID
	Url           string
	ContentSha256 string
	FetchedAt     pgtype.Timestamptz
}

type StudentGroup struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Code        string
	ExternalID  int32
	Course      int32
	Degree      string
	StudyForm   string
	Status      string
}

type SyncLog struct {
	Collection string
	ScopeID    string
	Lsn        int64
	Op         []byte
	RecordedAt pgtype.Timestamptz
}

type Thread struct {
	ID        string
	GroupCode string
	CreatedAt pgtype.Timestamptz
}

type ThreadEntry struct {
	ThreadID string
	EntryLsn int64
	AuthorID uuid.UUID
	Body     string
	HiddenAt pgtype.Timestamptz
	HiddenBy pgtype.UUID
}

type WebauthnCredential struct {
	CredentialID []byte
	PrincipalID  uuid.UUID
	PublicKey    []byte
	SignCount    int64
	CreatedAt    pgtype.Timestamptz
}
