// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAudit = `-- name: CountAudit :one
SELECT count(*)::bigint AS count FROM authz_audit
WHERE principal_id = $1 AND object_id = $2 AND allowed = $3
`

type CountAuditParams struct {
	PrincipalID pgtype.UUID
	ObjectID    string
	Allowed     bool
}

func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAudit, arg.PrincipalID, arg.ObjectID, arg.Allowed)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT count(*)::bigint AS count FROM student_group
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLessonChanges = `-- name: CountLessonChanges :one
SELECT count(*)::bigint AS count FROM lesson_change WHERE group_code = $1
`

func (q *Queries) CountLessonChanges(ctx context.Context, groupCode string) (int64, error) {
	row := q.db.QueryRow(ctx, countLessonChanges, groupCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLessons = `-- name: CountLessons :one
SELECT count(*)::bigint AS count FROM lesson
`

func (q *Queries) CountLessons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLessons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSyncOps = `-- name: CountSyncOps :one
SELECT count(*)::bigint AS count FROM sync_log
WHERE collection = $1 AND scope_id = $2
`

type CountSyncOpsParams struct {
	Collection string
	ScopeID    string
}

func (q *Queries) CountSyncOps(ctx context.Context, arg CountSyncOpsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncOps, arg.Collection, arg.ScopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentSnapshotHash = `-- name: CurrentSnapshotHash :one
SELECT s.content_sha256
FROM schedule_snapshot s
JOIN student_group g ON g.id = s.group_id
WHERE g.code = $1 AND s.superseded_at IS NULL
ORDER BY s.valid_from DESC
LIMIT 1
`

func (q *Queries) CurrentSnapshotHash(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, currentSnapshotHash, code)
	var content_sha256 string
	err := row.Scan(&content_sha256)
	return content_sha256, err
}

const deleteSyncOpsBefore = `-- name: DeleteSyncOpsBefore :exec
DELETE FROM sync_log WHERE collection = $1 AND scope_id = $2 AND lsn < $3
`

type DeleteSyncOpsBeforeParams struct {
	Collection string
	ScopeID    string
	Lsn        int64
}

func (q *Queries) DeleteSyncOpsBefore(ctx context.Context, arg DeleteSyncOpsBeforeParams) error {
	_, err := q.db.Exec(ctx, deleteSyncOpsBefore, arg.Collection, arg.ScopeID, arg.Lsn)
	return err
}

const findPublishedMiniapp = `-- name: FindPublishedMiniapp :one
SELECT version, bundle_sha256, signature, manifest
FROM miniapp_release
WHERE app_id = $1 AND status = 'published'
ORDER BY created_at DESC
LIMIT 1
`

type FindPublishedMiniappRow struct {
	Version      string
	BundleSha256 string
	Signature    string
	Manifest     []byte
}

func (q *Queries) FindPublishedMiniapp(ctx context.Context, appID string) (FindPublishedMiniappRow, error) {
	row := q.db.QueryRow(ctx, findPublishedMiniapp, appID)
	var i FindPublishedMiniappRow
	err := row.Scan(
		&i.Version,
		&i.BundleSha256,
		&i.Signature,
		&i.Manifest,
	)
	return i, err
}

const findPushReceipt = `-- name: FindPushReceipt :one
SELECT lsn FROM push_receipt
WHERE replica_id = $1 AND client_seq = $2
`

type FindPushReceiptParams struct {
	ReplicaID uuid.UUID
	ClientSeq int64
}

func (q *Queries) FindPushReceipt(ctx context.Context, arg FindPushReceiptParams) (int64, error) {
	row := q.db.QueryRow(ctx, findPushReceipt, arg.ReplicaID, arg.ClientSeq)
	var lsn int64
	err := row.Scan(&lsn)
	return lsn, err
}

const findSession = `-- name: FindSession :one
SELECT principal_id, secret_hash, expires_at FROM session WHERE id = $1
`

type FindSessionRow struct {
	PrincipalID uuid.UUID
	SecretHash  []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) FindSession(ctx context.Context, id uuid.UUID) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, id)
	var i FindSessionRow
	err := row.Scan(&i.PrincipalID, &i.SecretHash, &i.ExpiresAt)
	return i, err
}

const findSnapshot = `-- name: FindSnapshot :one
SELECT id FROM schedule_snapshot
WHERE group_id = $1 AND content_sha256 = $2
`

type FindSnapshotParams struct {
	GroupID       uuid.UUID
	ContentSha256 string
}

func (q *Queries) FindSnapshot(ctx context.Context, arg FindSnapshotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findSnapshot, arg.GroupID, arg.ContentSha256)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findThreadEntry = `-- name: FindThreadEntry :one
SELECT author_id, (hidden_at IS NOT NULL)::boolean AS hidden
FROM thread_entry
WHERE thread_id = $1 AND entry_lsn = $2
`

type FindThreadEntryParams struct {
	ThreadID string
	EntryLsn int64
}

type FindThreadEntryRow struct {
	AuthorID uuid.UUID
	Hidden   bool
}

func (q *Queries) FindThreadEntry(ctx context.Context, arg FindThreadEntryParams) (FindThreadEntryRow, error) {
	row := q.db.QueryRow(ctx, findThreadEntry, arg.ThreadID, arg.EntryLsn)
	var i FindThreadEntryRow
	err := row.Scan(&i.AuthorID, &i.Hidden)
	return i, err
}

const findThreadGroup = `-- name: FindThreadGroup :one
SELECT group_code FROM thread WHERE id = $1
`

func (q *Queries) FindThreadGroup(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, findThreadGroup, id)
	var group_code string
	err := row.Scan(&group_code)
	return group_code, err
}

const getLoroDoc = `-- name: GetLoroDoc :one
SELECT latest_snapshot, snapshot_version FROM loro_doc WHERE doc_id = $1
`

type GetLoroDocRow struct {
	LatestSnapshot  []byte
	SnapshotVersion int64
}

func (q *Queries) GetLoroDoc(ctx context.Context, docID string) (GetLoroDocRow, error) {
	row := q.db.QueryRow(ctx, getLoroDoc, docID)
	var i GetLoroDocRow
	err := row.Scan(&i.LatestSnapshot, &i.SnapshotVersion)
	return i, err
}

const hideThreadEntry = `-- name: HideThreadEntry :execrows
UPDATE thread_entry
SET hidden_at = $3, hidden_by = $4
WHERE thread_id = $1 AND entry_lsn = $2 AND hidden_at IS NULL
`

type HideThreadEntryParams struct {
	ThreadID string
	EntryLsn int64
	HiddenAt pgtype.Timestamptz
	HiddenBy pgtype.UUID
}

func (q *Queries) HideThreadEntry(ctx context.Context, arg HideThreadEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideThreadEntry,
		arg.ThreadID,
		arg.EntryLsn,
		arg.HiddenAt,
		arg.HiddenBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO authz_audit (id, principal_id, action, object_type, object_id, allowed, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditParams struct {
	ID          uuid.UUID
	PrincipalID pgtype.UUID
	Action      string
	ObjectType  string
	ObjectID    string
	Allowed     bool
	RecordedAt  pgtype.Timestamptz
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ID,
		arg.PrincipalID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Allowed,
		arg.RecordedAt,
	)
	return err
}

const insertHint = `-- name: InsertHint :exec
INSERT INTO hint_outbox (id, collection, scope_id, lsn, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHintParams struct {
	ID         uuid.UUID
	Collection string
	ScopeID    string
	Lsn        int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertHint(ctx context.Context, arg InsertHintParams) error {
	_, err := q.db.Exec(ctx, insertHint,
		arg.ID,
		arg.Collection,
		arg.ScopeID,
		arg.Lsn,
		arg.CreatedAt,
	)
	return err
}

type InsertLessonParams struct {
	ID         uuid.UUID
	SnapshotID uuid.UUID
	GroupID    uuid.UUID
	OccursOn   pgtype.Date
	StartsAt   pgtype.Time
	EndsAt     pgtype.Time
	Subject    string
	Kind       string
	Teacher    string
	Building   string
	Room       string
	WeekType   string
	SourceUrl  string
}

const insertLessonChange = `-- name: InsertLessonChange :exec
INSERT INTO lesson_change (id, group_code, author_id, kind, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLessonChangeParams struct {
	ID         uuid.UUID
	GroupCode  string
	AuthorID   uuid.UUID
	Kind       string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) InsertLessonChange(ctx context.Context, arg InsertLessonChangeParams) error {
	_, err := q.db.Exec(ctx, insertLessonChange,
		arg.ID,
		arg.GroupCode,
		arg.AuthorID,
		arg.Kind,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const insertMiniappRelease = `-- name: InsertMiniappRelease :exec
INSERT INTO miniapp_release (app_id, version, bundle_sha256, signature, manifest, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMiniappReleaseParams struct {
	AppID        string
	Version      string
	BundleSha256 string
	Signature    string
	Manifest     []byte
	Status       string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertMiniappRelease(ctx context.Context, arg InsertMiniappReleaseParams) error {
	_, err := q.db.Exec(ctx, insertMiniappRelease,
		arg.AppID,
		arg.Version,
		arg.BundleSha256,
		arg.Signature,
		arg.Manifest,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertPrincipal = `-- name: InsertPrincipal :exec
INSERT INTO principal (id, display_name, created_at)
VALUES ($1, $2, $3)
`

type InsertPrincipalParams struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPrincipal(ctx context.Context, arg InsertPrincipalParams) error {
	_, err := q.db.Exec(ctx, insertPrincipal, arg.ID, arg.DisplayName, arg.CreatedAt)
	return err
}

const insertPushReceipt = `-- name: InsertPushReceipt :exec
INSERT INTO push_receipt (replica_id, client_seq, collection, scope_id, lsn)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPushReceiptParams struct {
	ReplicaID  uuid.UUID
	ClientSeq  int64
	Collection string
	ScopeID    string
	Lsn        int64
}

func (q *Queries) InsertPushReceipt(ctx context.Context, arg InsertPushReceiptParams) error {
	_, err := q.db.Exec(ctx, insertPushReceipt,
		arg.ReplicaID,
		arg.ClientSeq,
		arg.Collection,
		arg.ScopeID,
		arg.Lsn,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (id, principal_id, secret_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	SecretHash  []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.PrincipalID,
		arg.SecretHash,
		arg.ExpiresAt,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :one
INSERT INTO schedule_snapshot (
    id, group_id, document_id, parser_version, content_sha256, lesson_count, valid_from
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertSnapshotParams struct {
	ID            uuid.UUID
	GroupID       uuid.UUID
	DocumentID    uuid.UUID
	ParserVersion string
	ContentSha256 string
	LessonCount   int32
	ValidFrom     pgtype.Timestamptz
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSnapshot,
		arg.ID,
		arg.GroupID,
		arg.DocumentID,
		arg.ParserVersion,
		arg.ContentSha256,
		arg.LessonCount,
		arg.ValidFrom,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSourceDocument = `-- name: InsertSourceDocument :one
INSERT INTO source_document (id, url, content_sha256, fetched_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertSourceDocumentParams struct {
	ID            uuid.UUID
	Url           string
	ContentSha256 string
	FetchedAt     pgtype.Timestamptz
}

func (q *Queries) InsertSourceDocument(ctx context.Context, arg InsertSourceDocumentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSourceDocument,
		arg.ID,
		arg.Url,
		arg.ContentSha256,
		arg.FetchedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSyncLog = `-- name: InsertSyncLog :exec
INSERT INTO sync_log (collection, scope_id, lsn, op, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSyncLogParams struct {
	Collection string
	ScopeID    string
	Lsn        int64
	Op         []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) InsertSyncLog(ctx context.Context, arg InsertSyncLogParams) error {
	_, err := q.db.Exec(ctx, insertSyncLog,
		arg.Collection,
		arg.ScopeID,
		arg.Lsn,
		arg.Op,
		arg.RecordedAt,
	)
	return err
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO thread (id, group_code, created_at) VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertThreadParams struct {
	ID        string
	GroupCode string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.Exec(ctx, insertThread, arg.ID, arg.GroupCode, arg.CreatedAt)
	return err
}

const insertThreadEntry = `-- name: InsertThreadEntry :exec
INSERT INTO thread_entry (thread_id, entry_lsn, author_id, body)
VALUES ($1, $2, $3, $4)
`

type InsertThreadEntryParams struct {
	ThreadID string
	EntryLsn int64
	AuthorID uuid.UUID
	Body     string
}

func (q *Queries) InsertThreadEntry(ctx context.Context, arg InsertThreadEntryParams) error {
	_, err := q.db.Exec(ctx, insertThreadEntry,
		arg.ThreadID,
		arg.EntryLsn,
		arg.AuthorID,
		arg.Body,
	)
	return err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :exec
INSERT INTO webauthn_credential (credential_id, principal_id, public_key, sign_count, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWebAuthnCredentialParams struct {
	CredentialID []byte
	PrincipalID  uuid.UUID
	PublicKey    []byte
	SignCount    int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, insertWebAuthnCredential,
		arg.CredentialID,
		arg.PrincipalID,
		arg.PublicKey,
		arg.SignCount,
		arg.CreatedAt,
	)
	return err
}

const latestSourceHash = `-- name: LatestSourceHash :one
SELECT content_sha256 FROM source_document WHERE url = $1 ORDER BY fetched_at DESC LIMIT 1
`

func (q *Queries) LatestSourceHash(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRow(ctx, latestSourceHash, url)
	var content_sha256 string
	err := row.Scan(&content_sha256)
	return content_sha256, err
}

const latestSyncOp = `-- name: LatestSyncOp :one
SELECT lsn, op FROM sync_log
WHERE collection = $1 AND scope_id = $2
ORDER BY lsn DESC
LIMIT 1
`

type LatestSyncOpParams struct {
	Collection string
	ScopeID    string
}

type LatestSyncOpRow struct {
	Lsn int64
	Op  []byte
}

func (q *Queries) LatestSyncOp(ctx context.Context, arg LatestSyncOpParams) (LatestSyncOpRow, error) {
	row := q.db.QueryRow(ctx, latestSyncOp, arg.Collection, arg.ScopeID)
	var i LatestSyncOpRow
	err := row.Scan(&i.Lsn, &i.Op)
	return i, err
}

const listLoroDocs = `-- name: ListLoroDocs :many
SELECT doc_id, latest_snapshot, snapshot_version FROM loro_doc ORDER BY doc_id
`

type ListLoroDocsRow struct {
	DocID           string
	LatestSnapshot  []byte
	SnapshotVersion int64
}

func (q *Queries) ListLoroDocs(ctx context.Context) ([]ListLoroDocsRow, error) {
	rows, err := q.db.Query(ctx, listLoroDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoroDocsRow
	for rows.Next() {
		var i ListLoroDocsRow
		if err := rows.Scan(&i.DocID, &i.LatestSnapshot, &i.SnapshotVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadEntryLSNs = `-- name: ListThreadEntryLSNs :many
SELECT entry_lsn FROM thread_entry WHERE thread_id = $1 ORDER BY entry_lsn
`

func (q *Queries) ListThreadEntryLSNs(ctx context.Context, threadID string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listThreadEntryLSNs, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var entry_lsn int64
		if err := rows.Scan(&entry_lsn); err != nil {
			return nil, err
		}
		items = append(items, entry_lsn)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedHints = `-- name: ListUnpublishedHints :many
SELECT id, collection, scope_id, lsn FROM hint_outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT 100
`

type ListUnpublishedHintsRow struct {
	ID         uuid.UUID
	Collection string
	ScopeID    string
	Lsn        int64
}

func (q *Queries) ListUnpublishedHints(ctx context.Context) ([]ListUnpublishedHintsRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedHints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpublishedHintsRow
	for rows.Next() {
		var i ListUnpublishedHintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Collection,
			&i.ScopeID,
			&i.Lsn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT credential_id, public_key, sign_count FROM webauthn_credential WHERE principal_id = $1
`

type ListWebAuthnCredentialsRow struct {
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
}

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, principalID uuid.UUID) ([]ListWebAuthnCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentials, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebAuthnCredentialsRow
	for rows.Next() {
		var i ListWebAuthnCredentialsRow
		if err := rows.Scan(&i.CredentialID, &i.PublicKey, &i.SignCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSyncScope = `-- name: LockSyncScope :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockSyncScope(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockSyncScope, hashtextextended)
	return err
}

const markHintPublished = `-- name: MarkHintPublished :exec
UPDATE hint_outbox SET published_at = $2 WHERE id = $1
`

type MarkHintPublishedParams struct {
	ID          uuid.UUID
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) MarkHintPublished(ctx context.Context, arg MarkHintPublishedParams) error {
	_, err := q.db.Exec(ctx, markHintPublished, arg.ID, arg.PublishedAt)
	return err
}

const minSyncLSN = `-- name: MinSyncLSN :one
SELECT COALESCE(MIN(lsn), 0)::bigint AS min_lsn FROM sync_log WHERE collection = $1 AND scope_id = $2
`

type MinSyncLSNParams struct {
	Collection string
	ScopeID    string
}

func (q *Queries) MinSyncLSN(ctx context.Context, arg MinSyncLSNParams) (int64, error) {
	row := q.db.QueryRow(ctx, minSyncLSN, arg.Collection, arg.ScopeID)
	var min_lsn int64
	err := row.Scan(&min_lsn)
	return min_lsn, err
}

const nextLSN = `-- name: NextLSN :one
SELECT (COALESCE(MAX(lsn), 0) + 1)::bigint AS next_lsn
FROM sync_log
WHERE collection = $1 AND scope_id = $2
`

type NextLSNParams struct {
	Collection string
	ScopeID    string
}

func (q *Queries) NextLSN(ctx context.Context, arg NextLSNParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextLSN, arg.Collection, arg.ScopeID)
	var next_lsn int64
	err := row.Scan(&next_lsn)
	return next_lsn, err
}

const setMiniappStatus = `-- name: SetMiniappStatus :exec
UPDATE miniapp_release SET status = $3 WHERE app_id = $1 AND version = $2
`

type SetMiniappStatusParams struct {
	AppID   string
	Version string
	Status  string
}

func (q *Queries) SetMiniappStatus(ctx context.Context, arg SetMiniappStatusParams) error {
	_, err := q.db.Exec(ctx, setMiniappStatus, arg.AppID, arg.Version, arg.Status)
	return err
}

const supersedeSnapshots = `-- name: SupersedeSnapshots :exec
UPDATE schedule_snapshot
SET superseded_at = $2
WHERE group_id = $1 AND superseded_at IS NULL AND content_sha256 <> $3
`

type SupersedeSnapshotsParams struct {
	GroupID       uuid.UUID
	SupersededAt  pgtype.Timestamptz
	ContentSha256 string
}

func (q *Queries) SupersedeSnapshots(ctx context.Context, arg SupersedeSnapshotsParams) error {
	_, err := q.db.Exec(ctx, supersedeSnapshots, arg.GroupID, arg.SupersededAt, arg.ContentSha256)
	return err
}

const syncOpsAfter = `-- name: SyncOpsAfter :many
SELECT lsn, op FROM sync_log
WHERE collection = $1 AND scope_id = $2 AND lsn > $3
ORDER BY lsn ASC
`

type SyncOpsAfterParams struct {
	Collection string
	ScopeID    string
	Lsn        int64
}

type SyncOpsAfterRow struct {
	Lsn int64
	Op  []byte
}

func (q *Queries) SyncOpsAfter(ctx context.Context, arg SyncOpsAfterParams) ([]SyncOpsAfterRow, error) {
	rows, err := q.db.Query(ctx, syncOpsAfter, arg.Collection, arg.ScopeID, arg.Lsn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncOpsAfterRow
	for rows.Next() {
		var i SyncOpsAfterRow
		if err := rows.Scan(&i.Lsn, &i.Op); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncScopeBytes = `-- name: SyncScopeBytes :one
SELECT COALESCE(SUM(octet_length(op)), 0)::bigint AS bytes
FROM sync_log
WHERE collection = $1 AND scope_id = $2
`

type SyncScopeBytesParams struct {
	Collection string
	ScopeID    string
}

func (q *Queries) SyncScopeBytes(ctx context.Context, arg SyncScopeBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, syncScopeBytes, arg.Collection, arg.ScopeID)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const updateLoroSnapshot = `-- name: UpdateLoroSnapshot :exec
UPDATE loro_doc
SET latest_snapshot = $2, snapshot_version = $3, updated_at = $4
WHERE doc_id = $1
`

type UpdateLoroSnapshotParams struct {
	DocID           string
	LatestSnapshot  []byte
	SnapshotVersion int64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateLoroSnapshot(ctx context.Context, arg UpdateLoroSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateLoroSnapshot,
		arg.DocID,
		arg.LatestSnapshot,
		arg.SnapshotVersion,
		arg.UpdatedAt,
	)
	return err
}

const updateWebAuthnSignCount = `-- name: UpdateWebAuthnSignCount :exec
UPDATE webauthn_credential SET sign_count = $2 WHERE credential_id = $1
`

type UpdateWebAuthnSignCountParams struct {
	CredentialID []byte
	SignCount    int64
}

func (q *Queries) UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnSignCount, arg.CredentialID, arg.SignCount)
	return err
}

const upsertInstitute = `-- name: UpsertInstitute :one
INSERT INTO institute (id, code, name)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertInstituteParams struct {
	ID   uuid.UUID
	Code string
	Name string
}

func (q *Queries) UpsertInstitute(ctx context.Context, arg UpsertInstituteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertInstitute, arg.ID, arg.Code, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertLoroDoc = `-- name: UpsertLoroDoc :exec
INSERT INTO loro_doc (doc_id, latest_snapshot, snapshot_version, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (doc_id) DO UPDATE SET
    latest_snapshot = EXCLUDED.latest_snapshot,
    snapshot_version = EXCLUDED.snapshot_version,
    updated_at = EXCLUDED.updated_at
`

type UpsertLoroDocParams struct {
	DocID           string
	LatestSnapshot  []byte
	SnapshotVersion int64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertLoroDoc(ctx context.Context, arg UpsertLoroDocParams) error {
	_, err := q.db.Exec(ctx, upsertLoroDoc,
		arg.DocID,
		arg.LatestSnapshot,
		arg.SnapshotVersion,
		arg.UpdatedAt,
	)
	return err
}

const upsertStudentGroup = `-- name: UpsertStudentGroup :one
INSERT INTO student_group (
    id, institute_id, code, external_id, course, degree, study_form, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (code) DO UPDATE SET
    institute_id = EXCLUDED.institute_id,
    external_id = EXCLUDED.external_id,
    course = EXCLUDED.course,
    degree = EXCLUDED.degree,
    study_form = EXCLUDED.study_form,
    status = EXCLUDED.status
RETURNING id
`

type UpsertStudentGroupParams struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Code        string
	ExternalID  int32
	Course      int32
	Degree      string
	StudyForm   string
	Status      string
}

func (q *Queries) UpsertStudentGroup(ctx context.Context, arg UpsertStudentGroupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertStudentGroup,
		arg.ID,
		arg.InstituteID,
		arg.Code,
		arg.ExternalID,
		arg.Course,
		arg.Degree,
		arg.StudyForm,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
