import React from "react";
import {DataComponent,DataTable,ReportSection,RichNarrative,useDataApp} from "../../data-app-public.jsx";
const official="https://www.timacad.ru/about/sveden/document/rezhim-zaniatii-obuchaiushchikhsia";
const sourcePreviews={ [official]:{title:"Расписание РГАУ-МСХА",summary:"На странице опубликованы документы текущего семестра и ссылка на электронное расписание. Архивные документы не включены в текущий каталог приложения.",source:"РГАУ-МСХА",date:"2026-09-19",approvedForReport:true} };
const mb=n=>`${(n/1024/1024).toFixed(2)} МиБ`;
const kb=n=>`${(n/1024).toFixed(0)} КиБ`;
export function ReportContent(){
  const {snapshot,visible,appTitle,canEdit,mode,setAppTitle}=useDataApp();
  const s=snapshot.queries.summary.rows[0],coverage=snapshot.queries.coverage.rows,security=snapshot.queries.security.rows;
  return <article className="report-content" aria-label="Отчёт о разработке ТИМ Кампус">
    <header className="report-hero"><h1 data-data-app-title contentEditable={canEdit&&mode==="edit"} suppressContentEditableWarning onBlur={e=>{if(canEdit&&mode==="edit")setAppTitle(e.currentTarget.textContent.trim()||appTitle)}}>{appTitle}</h1></header>
    {visible("coverage-summary")&&<ReportSection id="coverage-summary" title="Главное" queryId="summary" sourceRows={[s]} showHeading={false}>
      <RichNarrative id="coverage-summary:body" value={`## Главное\n\nВместо демонстрационных пар приложение использует официальный каталог **${s.groups} групп** и **${(s.lessons/1000).toFixed(1)} тыс. занятий** на конкретные даты. У ${s.withLessons} групп есть занятия в загруженном периоде; у ${s.withoutLessons} источник не содержит занятий. Это ограничение покрытия, а не доказательство свободного дня.\n\nПереработаны навигация, расписание, карта и личный планировщик. Android APK собран в release-режиме, подпись проверена. Веб-сборка повторно открылась с сохранёнными занятиями после остановки сервера. Университетские пропуска, совместный режим старосты и нативные виджеты пока не подключены.`}/>
    </ReportSection>}
    {visible("coverage-table")&&<DataComponent id="coverage-table" queryId="coverage" kind="table" title="Где есть расписание и документы" sourceRows={coverage} displayRows={coverage}>
      <DataTable rows={coverage} caption="Покрытие подразделений" compactNumbers={false} columns={[{field:"institute",label:"Подразделение",renderCell:value=><span style={{display:"block",whiteSpace:"normal",minWidth:180,maxWidth:270}}>{value}</span>},{field:"groups",label:"Групп"},{field:"withLessons",label:"С занятиями"},{field:"withoutLessons",label:"Без занятий"},{field:"documents",label:"PDF"}]}/>
    </DataComponent>}
    <RichNarrative id="coverage:limits" value="Центр цифровой трансформации опубликован отдельным PDF, но не выделен отдельным подразделением в электронном каталоге. Для него нельзя приравнивать отсутствие отдельной строки групп к отсутствию расписания. Документы доступны из приложения. Полнота данных по всем видам обучения ещё требует сверки с PDF."/>
    {visible("storage-summary")&&<ReportSection id="storage-summary" title="Расписание не загружает весь кампус на телефон" queryId="summary" sourceRows={[s]} showHeading={false}>
      <RichNarrative id="storage-summary:body" value={`## Расписание не загружает весь кампус на телефон\n\nПолный набор групп занимает ${mb(s.allShardBytes)} в JSON. Клиент получает каталог ${kb(s.catalogBytes)} и сохраняет не более трёх открытых расписаний. Три самых крупных файла вместе — ${kb(s.maxThreeShardBytes)}. Эти значения описывают полезные данные до сжатия; размер установленного приложения и служебные расходы хранилища сюда не входят.\n\nЗадачи, заметки и личные планы сохраняются на устройстве. Экспорт и восстановление JSON позволяют перенести свои записи. Поиск и переключение дат используют уже загруженные данные. Заявления о 0 мс или 120 FPS не подтверждались измерениями.`}/>
    </ReportSection>}
    {visible("security-summary")&&<ReportSection id="security-summary" title="Исправлены опасные границы старого backend" queryId="security" sourceRows={security} showHeading={false}>
      <RichNarrative id="security-summary:body" value="## Исправлены опасные границы старого backend\n\nCodex Security зафиксировал пять исходных проблем: четыре medium и одну low. Среди них — подделка роли старосты, анонимный запуск импорта и доступ к хранилищам через опубликованные порты. Исправления внесены; соответствующие Go-тесты прошли. Незавершённые совместные сервисы отключены до появления проверяемой идентичности.\n\nПокрытие скана частичное. Установка APK на физическом устройстве, эксплуатация работающего сервера и нагрузка всего кампуса не проверены. Нельзя трактовать этот результат как полный аудит безопасности или готовность всех заявленных интеграций."/>
    </ReportSection>}
    {visible("security-table")&&<DataComponent id="security-table" queryId="security" kind="table" title="Исходные находки Codex Security" sourceRows={security} displayRows={security}><DataTable rows={security} caption="Находки исходного скана" searchable={false} columns={[{field:"finding",label:"Проблема",renderCell:value=><span style={{display:"block",whiteSpace:"normal",minWidth:200,maxWidth:520}}>{value}</span>},{field:"severity",label:"Оценка"}]}/></DataComponent>}
    <RichNarrative id="delivery:remaining" value="## Границы бета-выпуска и следующие шаги\n\n- APK собран и подпись проверена. Проверить установку и работу на физическом Android-устройстве.\n- Офлайн-запуск готовой веб-сборки проверен. Публикация предусматривает сверку commit и SHA-256 всех файлов; квитанция включается в релиз.\n- Дополнить сверку всех институтов и курсов по официальным документам; явно показать пробелы источника.\n- Для режима старосты внедрить вход и проверяемое членство в группе. Для Wallet/NFC и системных виджетов нужны отдельные интеграции и платформенные расширения.\n\nВыбран React с Capacitor, поскольку это существующая рабочая кодовая база. Переход на KMP или Rust не реализован. Схема кампуса основана на предоставленном плане; точные маршруты между этажами и занятость помещений не подтверждены."/>
    <RichNarrative id="methods:body" sourcePreviews={sourcePreviews} value={`## Как проверялись данные\n\n[Официальная страница расписания](${official}) содержит документы семестра и ссылку на [электронное расписание](https://eg.timacad.ru/schedule/groups/). Снимок источника проверен ${new Intl.DateTimeFormat("ru-RU",{dateStyle:"long",timeStyle:"short",timeZone:"Europe/Moscow"}).format(new Date(s.checkedAt))} МСК; период занятий — ${s.window.from} — ${s.window.to}. Парсер сохраняет конкретные даты, время, преподавателя и аудиторию без выдуманного повторения по неделям.\n\nПовторный разбор сохранённых страниц всех ${s.revalidatedGroups} групп вернул те же занятия с ${s.parserFailures} ошибками. Обновления ограничены HTTPS-источниками, проверяют схему и контрольные суммы. Отсутствующие сведения не заменяются демонстрационными.\n\nМетодика, точные числа и пути к воспроизводящим скриптам доступны через действия источников у таблиц и разделов. При ошибке официального сайта приложение сохраняет последний проверенный снимок и явно показывает его дату. Отчёт описывает проверенную бета-версию, а не завершение всех функций первоначального замысла.`}/>
  </article>
}
