import { useEffect, useMemo, useRef, useState, type ReactNode, type FormEvent } from "react"
import Icon from "./components/next/Icon"
import OrbitArt from "./components/next/OrbitArt"
import CampusMap from "./components/next/CampusMap"
import BackupRestore from "./components/next/BackupRestore"
import { useStudent, moscowToday, shortDate, addDays, downloadText, exportPlans, type Task, type Plan } from "./lib/student-store"
import { useScheduleData, safeSource, type Lesson } from "./lib/campus-data"

type Page = "home" | "schedule" | "campus" | "planner" | "services"
type Modal = "group" | "search" | "task" | "plan" | "settings" | "sources" | "integration" | null
const navigation: { id: Page; label: string; icon: string }[] = [
  { id: "home", label: "Мой день", icon: "home" }, { id: "schedule", label: "Расписание", icon: "calendar" },
  { id: "campus", label: "Кампус", icon: "map" }, { id: "planner", label: "Мои дела", icon: "note" }, { id: "services", label: "Сервисы", icon: "grid" },
]
const services = [
  { title: "Личный кабинет", description: "Учебные сервисы и ЭИОС университета", icon: "person", url: "https://www.timacad.ru/students", tag: "УЧЁБА" },
  { title: "Электронная библиотека", description: "Учебники, научные работы и электронный каталог", icon: "book", url: "https://elib.timacad.ru/", tag: "ЗНАНИЯ" },
  { title: "Новости академии", description: "События и объявления на официальном сайте", icon: "globe", url: "https://www.timacad.ru/", tag: "КАМПУС" },
  { title: "Студентам", description: "Информация и возможности для студентов", icon: "grid", url: "https://www.timacad.ru/students", tag: "ВОЗМОЖНОСТИ" },
  { title: "Расписание вуза", description: "Первоисточник документов всех институтов", icon: "calendar", url: "https://www.timacad.ru/about/sveden/document/rezhim-zaniatii-obuchaiushchikhsia", tag: "ИСТОЧНИК" },
  { title: "Территория академии", description: "Схема кампуса на сайте университета", icon: "map", url: "https://www.timacad.ru/student-life/skhema-territorii", tag: "НАВИГАЦИЯ" },
]
function ModalFrame({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(() => { const d = ref.current; d?.showModal(); return () => d?.close() }, [])
  return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }}><div className="modal-content"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Закрыть окно" onClick={onClose}><Icon name="close"/></button></div>{children}</div></dialog>
}
function Empty({ icon, title, children, action }: { icon: string; title: string; children: ReactNode; action?: ReactNode }) { return <div className="empty-state"><div className="empty-icon"><Icon name={icon} size={28}/></div><h3>{title}</h3><p>{children}</p>{action}</div> }
export default function App() {
  const { data, ready, storageError, update } = useStudent()
  const { catalog, groupData, syncing, syncError, refresh } = useScheduleData(data.group)
  const [page, setPage] = useState<Page>("home"), [modal, setModal] = useState<Modal>(null)
  const [today, setToday] = useState(moscowToday), [date, setDate] = useState(today)
  const [query, setQuery] = useState(""), [institute, setInstitute] = useState(""), [course, setCourse] = useState("")
  const [toast, setToast] = useState(""), [detail, setDetail] = useState<Lesson | null>(null)
  const [editPlan, setEditPlan] = useState<Plan | null>(null), [integration, setIntegration] = useState("")
  const [taskFilter, setTaskFilter] = useState("active"), [online, setOnline] = useState(navigator.onLine)
  const [light, setLight] = useState(() => { try { return localStorage.getItem("tim-theme-v4") === "light" } catch { return false } })
  useEffect(() => { document.documentElement.dataset.theme = light ? "light" : "dark"; document.querySelectorAll('meta[name="theme-color"]').forEach(e => e.setAttribute("content", light ? "#f1f1e9" : "#111410")); try { localStorage.setItem("tim-theme-v4", light ? "light" : "dark") } catch {} }, [light])
  useEffect(() => { const fn = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setQuery(""); setModal("search") } }; window.addEventListener("keydown", fn); return () => window.removeEventListener("keydown", fn) }, [])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 4000); return () => clearTimeout(timer) }, [toast])
  useEffect(() => { const timer = setInterval(() => setToday(moscowToday()), 60000); const fn = () => setOnline(navigator.onLine); window.addEventListener("online", fn); window.addEventListener("offline", fn); return () => { clearInterval(timer); window.removeEventListener("online", fn); window.removeEventListener("offline", fn) } }, [])
  const groups = useMemo(() => Object.entries(catalog.groups), [catalog])
  const filteredGroups = groups.filter(([id, g]) => `${id} ${g.institute}`.toLowerCase().includes(query.toLowerCase()) && (modal !== "group" || ((!institute || g.instituteId === institute) && (!course || String(g.course) === course)))).sort(([a], [b]) => Number(data.favorites.includes(b)) - Number(data.favorites.includes(a)) || a.localeCompare(b, "ru"))
  const monday = addDays(date, -(new Date(date + "T12:00:00Z").getUTCDay() + 6) % 7)
  const days = Array.from({ length: 7 }, (_, i) => addDays(monday, i))
  const lessons = groupData?.schedule?.find(d => d.date === date)?.classes || []
  const plans = data.plans.filter(p => p.date === date).sort((a, b) => a.start.localeCompare(b.start))
  const activeTasks = data.tasks.filter(t => !t.done)
  const checked = catalog.meta.checkedAt || catalog.meta.lastSyncTime
  const scheduleWindow = groupData?.window || catalog.meta.scheduleWindow
  const outsideWindow = !!scheduleWindow && (date < scheduleWindow.from || date > scheduleWindow.to)
  function go(next: Page) { setPage(next); globalThis.scrollTo({ top: 0, behavior: "instant" }); setModal(null) }
  function openGroup() { setQuery(""); setModal("group") }
  function openPlan(plan?: Plan) { setEditPlan(plan || null); setModal("plan") }
  function toggleTask(t: Task) { update(d => ({ tasks: d.tasks.map(item => item.id === t.id ? { ...item, done: !item.done } : item) })) }
  function chooseGroup(id: string) { update({ group: id }); setModal(null); setToast(`Группа ${id} выбрана`); setDate(today) }
  function sourceState() { return groupData?.stale ? "Сохранённая версия · обновление недоступно" : syncing ? "Проверяем обновления" : !online ? "Офлайн · сохранённые данные" : checked ? `Проверено ${new Date(checked).toLocaleDateString("ru-RU", { day: "numeric", month: "short" })}` : "Источник требует проверки" }
  function taskRows(items: Task[]) { return <div className="task-list">{items.map(t => <div className={`task-row ${t.done ? "done" : ""}`} key={t.id}><button className="task-checkbox" aria-label={`${t.done ? "Вернуть" : "Выполнить"}: ${t.title}`} aria-pressed={t.done} onClick={() => toggleTask(t)}>{t.done && <Icon name="check" size={14}/>}</button><div><span>{t.title}</span><small className={t.date && t.date < today && !t.done ? "overdue" : ""}>{t.kind === "homework" ? "Домашнее задание" : "Личное"}{t.date && ` · ${shortDate(t.date)}`}</small></div><button className="icon-button delete-task" aria-label={`Удалить: ${t.title}`} onClick={() => { update(d => ({ tasks: d.tasks.filter(item => item.id !== t.id) })); setToast("Задача удалена") }}><Icon name="trash" size={16}/></button></div>)}</div> }
  function schedulePanel(full = false) { return <section className={`panel schedule-panel ${full ? "full" : ""}`}>
    <div className="section-heading"><div><span className="eyebrow">ВАШ УЧЕБНЫЙ РИТМ</span><h2>{full ? "Расписание занятий" : "Расписание"}</h2></div>{!full ? <button className="text-button" onClick={() => go("schedule")}>Вся неделя <Icon name="arrow" size={16}/></button> : <button className="button small" onClick={() => openPlan()}><Icon name="plus" size={16}/>Личный план</button>}</div>
    <div className="week-heading"><button className="icon-button" aria-label="Предыдущая неделя" onClick={() => setDate(addDays(date, -7))}><Icon name="left" size={17}/></button><span>{shortDate(monday, { day: "numeric" })} — {shortDate(addDays(monday, 6))}</span><button className="icon-button" aria-label="Следующая неделя" onClick={() => setDate(addDays(date, 7))}><Icon name="right" size={17}/></button><button className="text-button today-button" onClick={() => setDate(today)}>Сегодня</button>{full && <input type="date" value={date} aria-label="Выбрать дату расписания" min="2000-01-01" max="2100-12-31" onInput={e => { if (e.currentTarget.validity.valid && e.currentTarget.value) setDate(e.currentTarget.value) }} onChange={e => { if (e.target.validity.valid && e.target.value) setDate(e.target.value) }}/>}</div>
    {groupData?.stale && <p className="notice" role="status">Не удалось загрузить обновлённое расписание. Показана прежняя сохранённая версия{groupData.checkedAt ? ` от ${new Date(groupData.checkedAt).toLocaleDateString("ru-RU")}` : ""}. <button className="text-button" onClick={refresh}>Повторить</button></p>}<div className="week-strip">{days.map(d => <button key={d} aria-pressed={d === date} className={`day ${d === date ? "active" : ""} ${d === today ? "today" : ""}`} onClick={() => setDate(d)}><span>{shortDate(d, { weekday: "short" })}</span><strong>{Number(d.slice(8))}</strong><i/></button>)}</div>
    {!data.group ? <Empty icon="calendar" title="Каждый день начинается с плана" action={<button className="button primary" onClick={openGroup}>Выбрать свою группу <Icon name="arrow" size={16}/></button>}>Подключите расписание своей группы.<br/>Пары, преподаватели и аудитории — в одном месте.</Empty> : !groupData ? <Empty icon="refresh" title="Загружаем расписание">После загрузки оно будет доступно офлайн.</Empty> : outsideWindow ? <Empty icon="calendar" title="Эта дата вне загруженного периода" action={<a className="button" href={safeSource(groupData.sourceUrl)} target="_blank" rel="noreferrer">Первоисточник <Icon name="diagonal" size={16}/></a>}>Доступны даты {scheduleWindow && shortDate(scheduleWindow.from)} — {scheduleWindow && shortDate(scheduleWindow.to)}.</Empty> : groupData.status === "fetch-failed" ? <Empty icon="refresh" title="Расписание пока недоступно" action={<button className="button" onClick={refresh}>Повторить загрузку</button>}>Не удалось проверить расписание этой группы.</Empty> : lessons.length ? <div className="lesson-list">{lessons.map((l, i) => <button className="lesson-row" key={`${l.id}-${i}`} onClick={() => setDetail(l)}><div className="lesson-time"><strong>{l.start}</strong><span>{l.end}</span></div><div className={`lesson-mark ${l.type}`}/><div className="lesson-info"><div className="lesson-type">{({ lecture: "Лекция", practice: "Практика", lab: "Лабораторная" } as Record<string, string>)[l.type] || "Занятие"}</div><h3>{l.subject}</h3><p>{l.teacher || "Преподаватель не указан"}</p><span><Icon name="pin" size={13}/>{[l.building, l.room && `ауд. ${l.room}`].filter(Boolean).join(" · ") || "Аудитория не указана"}</span></div><Icon name="diagonal" size={17}/></button>)}</div> : <Empty icon="coffee" title="В расписании нет занятий">На {shortDate(date)} источник не содержит пар для группы {data.group}. Проверьте объявления института о возможных изменениях.</Empty>}
    {!!plans.length && <div className="personal-plans"><span className="eyebrow">ЛИЧНЫЕ ПЛАНЫ</span>{plans.map(p => <button className={`personal-plan ${p.cancelled ? "cancelled" : ""}`} key={p.id} onClick={() => openPlan(p)}><Icon name="calendar" size={17}/><span><strong>{p.title}</strong><small>{p.start}–{p.end}{p.room && ` · ${p.room}`}{p.cancelled && " · отменён"}</small></span><Icon name="edit" size={16}/></button>)}</div>}
    <div className="panel-bottom"><span><i className={`status-dot ${online ? "" : "offline"}`}/>{sourceState()}</span><button className="text-button" onClick={() => setModal("sources")}>Об источниках <Icon name="diagonal" size={13}/></button></div></section> }
  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Перейти к содержимому</a>
    <aside className="sidebar"><button className="brand" onClick={() => go("home")} aria-label="ТИМ Кампус — главная"><span className="brand-symbol">т.</span><span>ТИМ<span className="brand-caption">КАМПУС</span></span><i>β</i></button><div className="sidebar-label">ТВОЯ ТОЧКА РОСТА</div><nav aria-label="Основная навигация">{navigation.map((n,i) => <button key={n.id} className={`nav-item ${page === n.id ? "active" : ""}`} aria-current={page === n.id ? "page" : undefined} onClick={() => go(n.id)}><Icon name={n.icon}/><span>{n.label}</span><small>0{i+1}</small></button>)}</nav><div className="sidebar-bottom"><div className="campus-id"><div className="small-orbit">✳</div><span>Тимирязевка<small>Место, где ты растёшь.</small></span></div><button className="nav-item" onClick={() => setModal("settings")}><Icon name="settings"/><span>Настройки</span></button><span className="sidebar-footer">НЕЗАВИСИМЫЙ СТУДЕНЧЕСКИЙ ПРОЕКТ</span></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Кампус <span>/</span> <strong>{navigation.find(n => n.id === page)?.label}</strong></div><div className="top-actions"><button className="search-trigger" aria-label="Поиск по приложению" onClick={() => { setQuery(""); setModal("search") }}><Icon name="search" size={18}/><span>Поиск</span><kbd>Ctrl K</kbd></button><button className="group-button" onClick={openGroup}><Icon name="person" size={16}/><span>{data.group || "Моя группа"}</span><Icon name="down" size={14}/></button><button className="avatar" aria-label="Профиль и настройки" onClick={() => setModal("settings")}>{data.name ? data.name.slice(0, 1).toUpperCase() : "Я"}</button></div></header>
    <main id="main-content" tabIndex={-1}>
      {(storageError || !online) && <div className="notice" role="status"><Icon name={storageError ? "shield" : "globe"} size={17}/>{storageError || "Вы офлайн. Сохранённое расписание, карта и личные дела доступны."}</div>}
      {page === "home" && <><div className="page-heading"><div><span className="eyebrow">{shortDate(today, { weekday: "long", day: "numeric", month: "long" }).toUpperCase()}</span><h1>{data.name ? `Привет, ${data.name}.` : "Твой день. Твой кампус."}<span className="heading-star">✳</span></h1></div><span className="semester-label">{catalog.meta.currentTerm ? `${catalog.meta.currentTerm.semester} СЕМЕСТР / ${catalog.meta.currentTerm.academicYear}` : "ТИМИРЯЗЕВСКАЯ АКАДЕМИЯ"}</span></div>
      <section className="hero"><div className="hero-copy"><div className="hero-kicker"><i/> БОЛЬШЕ, ЧЕМ РАСПИСАНИЕ</div><h2>Учёба в своём<br/><em>ритме.</em></h2><p>Меньше суеты. Больше возможностей.<br/>Вся твоя университетская жизнь — рядом.</p><button className="button primary" onClick={() => data.group ? go("schedule") : openGroup()}>{data.group ? "Моё расписание" : "Найти свою группу"}<Icon name="arrow" size={18}/></button></div><OrbitArt/><span className="hero-index">01 / РАСТИ ВМЕСТЕ С ТИМ</span></section>
      <div className="dashboard-grid">{schedulePanel()}<section className="panel tasks-panel"><div className="section-heading"><div><span className="eyebrow">ОСВОБОДИ МЫСЛИ</span><h2>В фокусе <span className="count">{activeTasks.length}</span></h2></div><button className="icon-button add-circle" aria-label="Добавить задачу" onClick={() => setModal("task")} disabled={!ready}><Icon name="plus"/></button></div>{activeTasks.length ? taskRows(activeTasks.slice(0, 4)) : <Empty icon="check" title="Место для важных дел">Задания, дедлайны или просто<br/>то, что не хочется забыть.</Empty>}<button className="add-task-inline" onClick={() => setModal("task")} disabled={!ready}><Icon name="plus" size={17}/>Добавить задачу</button><div className="focus-bottom"><div className="focus-lines">{Array.from({ length: 13 }, (_, i) => <span key={i} style={{ height: `${20 + Math.sin(i / 2) * 15}px` }}/>)}</div><p>Большие перемены<br/>начинаются с маленьких шагов.</p></div><button className="text-button" onClick={() => go("planner")}>Все мои дела <Icon name="arrow" size={16}/></button></section></div>
      <div className="bottom-grid"><section className="panel campus-preview"><div className="section-heading"><div><span className="eyebrow">ЗНАКОМОЕ МЕСТО. НОВЫЙ ВЗГЛЯД.</span><h2>Встретимся в кампусе</h2></div><button className="icon-button" aria-label="Перейти к карте" onClick={() => go("campus")}><Icon name="diagonal"/></button></div><CampusMap compact onExpand={() => go("campus")}/></section><section className="panel quick-services"><div className="section-heading"><div><span className="eyebrow">ВСЁ ПОД РУКОЙ</span><h2>Быстрый доступ</h2></div><button className="text-button" onClick={() => go("services")}>Все <Icon name="arrow" size={16}/></button></div>{services.slice(0, 3).map(s => <a className="service-link" href={s.url} key={s.title} target="_blank" rel="noreferrer"><span className="service-icon"><Icon name={s.icon}/></span><span>{s.title}<small>{s.tag}</small></span><Icon name="diagonal" size={17}/></a>)}</section></div></>}
      {page === "schedule" && <><div className="page-heading"><div><span className="eyebrow">УЧЁБА БЕЗ ЛИШНЕГО ШУМА</span><h1>Расписание<span className="heading-star">↗</span></h1></div><button className="button" onClick={openGroup}>{data.group || "Выбрать группу"}<Icon name="down" size={16}/></button></div><div className="schedule-layout">{schedulePanel(true)}<aside className="schedule-aside panel"><span className="eyebrow">МОЯ ГРУППА</span><h2>{data.group || "Давай знакомиться"}</h2><p>{groupData?.institute || "Выбери институт, курс и группу. Мы сохраним выбор на этом устройстве."}</p>{groupData?.course && <span className="tag">{groupData.course} курс</span>}<hr/><h3>Изменились планы?</h3><p>Запиши перенос или отмену в личный план. Такая запись видна только тебе.</p><button className="button" onClick={() => openPlan()}><Icon name="plus" size={16}/>Добавить запись</button><button className="text-button" onClick={() => { setIntegration("Режим старосты и изменения группы"); setModal("integration") }}>Возможности старосты <Icon name="arrow" size={16}/></button><hr/><div className="source-card"><Icon name="shield"/><div><strong>Проверяемый источник</strong><p>Оригинал доступен из карточки занятия.</p></div></div><button className="text-button" onClick={() => setModal("sources")}>Состояние данных <Icon name="diagonal" size={16}/></button></aside></div></>}
      {page === "campus" && <><div className="page-heading"><div><span className="eyebrow">ТВОЯ ТЕРРИТОРИЯ</span><h1>Открывай кампус<span className="heading-star">⌖</span></h1></div><span className="semester-label">КОРПУСА · САДЫ · МЕСТА</span></div><section className="panel map-panel"><CampusMap/></section></>}
      {page === "planner" && <><div className="page-heading"><div><span className="eyebrow">В ГОЛОВЕ СТАЛО СВОБОДНЕЕ</span><h1>Мои дела<span className="heading-star">✳</span></h1></div><button className="button primary" onClick={() => setModal("task")} disabled={!ready}><Icon name="plus" size={18}/>Новая задача</button></div><div className="planner-grid"><section className="panel planner-tasks"><div className="section-heading"><h2>Задачи и домашние задания</h2><span className="count">{data.tasks.length}</span></div><div className="chips">{[{ id: "active", title: "В работе" }, { id: "done", title: "Готово" }, { id: "all", title: "Все" }].map(f => <button className={`chip ${taskFilter === f.id ? "active" : ""}`} key={f.id} onClick={() => setTaskFilter(f.id)}>{f.title}</button>)}</div>{taskRows(data.tasks.filter(t => taskFilter === "all" || (taskFilter === "done" ? t.done : !t.done)))}{!data.tasks.filter(t => taskFilter === "all" || (taskFilter === "done" ? t.done : !t.done)).length && <Empty icon="check" title={taskFilter === "done" ? "Первые победы ещё впереди" : "С чистого листа"}>Добавь дело и начни с небольшого шага.</Empty>}</section><section className="panel notes-panel"><div className="section-heading"><h2>Заметка себе</h2><Icon name="edit" size={18}/></div><textarea className="notebook" aria-label="Личная заметка" placeholder="Идея, конспект, ссылка… Здесь можно просто думать." value={data.notes} maxLength={50000} disabled={!ready} onChange={e => update({ notes: e.target.value })}/><div className="panel-bottom"><span><Icon name="shield" size={13}/>Только на этом устройстве</span><small>{data.notes.length.toLocaleString("ru-RU")} / 50 000</small></div></section><section className="panel personal-planner"><div className="section-heading"><h2>Личный календарь</h2><div className="heading-actions"><button className="icon-button" aria-label="Экспорт личных планов в календарь" disabled={!data.plans.some(p => !p.cancelled)} onClick={() => { exportPlans(data.plans); setToast("Файл календаря подготовлен") }}><Icon name="download"/></button><button className="button small" onClick={() => openPlan()}><Icon name="plus" size={16}/>Запись</button></div></div>{!data.plans.length ? <Empty icon="calendar" title="Планы, которые принадлежат тебе">Встречи, подготовка к экзамену и личные изменения расписания. Можно экспортировать в календарь.</Empty> : <div>{[...data.plans].sort((a,b) => (a.date+a.start).localeCompare(b.date+b.start)).map(p => <button key={p.id} className={`personal-plan ${p.cancelled ? "cancelled" : ""}`} onClick={() => openPlan(p)}><Icon name="calendar"/><span><strong>{p.title}</strong><small>{shortDate(p.date)} · {p.start}–{p.end} · {p.cancelled ? "Отменён" : p.room || "Личный план"}</small></span><Icon name="edit" size={16}/></button>)}</div>}</section></div></>}
      {page === "services" && <><div className="page-heading"><div><span className="eyebrow">УНИВЕРСИТЕТ БЛИЖЕ, ЧЕМ КАЖЕТСЯ</span><h1>Один кампус. Всё рядом.</h1></div></div><div className="service-grid">{services.map((s, i) => <a href={s.url} target="_blank" rel="noreferrer" className="panel service-card" key={s.title}><div><span className="service-icon"><Icon name={s.icon} size={24}/></span><span className="eyebrow">0{i+1} / {s.tag}</span><Icon name="diagonal" size={20}/></div><h2>{s.title}</h2><p>{s.description}</p><small>Официальный ресурс ↗</small></a>)}</div><section className="panel integrations"><span className="eyebrow">СЛЕДУЮЩАЯ ГЛАВА</span><h2>Больше возможностей — с участием университета</h2><p>Эти сервисы требуют подтверждённого доступа и подключения систем вуза.</p><div className="integration-list">{["Студенческий билет и Wallet", "Режим старосты и изменения группы", "Свободные аудитории", "Мини-приложения и сообщества", "Системные виджеты iOS и Android"].map(label => <button key={label} onClick={() => { setIntegration(label); setModal("integration") }}><Icon name="grid" size={17}/>{label}<span>Что нужно</span><Icon name="arrow" size={16}/></button>)}</div></section></>}
      <footer className="app-footer"><span>ТИМ КАМПУС <i>·</i> Точка роста — здесь.</span><button className="text-button" onClick={() => setModal("sources")}>Данные и источники <Icon name="diagonal" size={13}/></button></footer>
    </main></div>
    <nav className="mobile-nav" aria-label="Мобильная навигация">{navigation.map(n => <button key={n.id} className={page === n.id ? "active" : ""} onClick={() => go(n.id)} aria-current={page === n.id ? "page" : undefined}><Icon name={n.icon}/><span>{n.label}</span></button>)}</nav>
    {modal && <ModalFrame title={({ group: "Твоя группа", search: "Что найдём?", task: "Небольшой шаг вперёд", plan: editPlan ? "Личный план" : "Новая запись", settings: "Твоё пространство", sources: "Данные и источники", integration } as Record<string,string>)[modal]} onClose={() => setModal(null)}>
      {(modal === "group" || modal === "search") && <><label className="search-input large"><Icon name="search"/><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder={modal === "group" ? "Номер группы или название института" : "Группа, раздел или преподаватель…"}/></label>{modal === "group" && <div className="filter-row"><select aria-label="Институт" value={institute} onChange={e => setInstitute(e.target.value)}><option value="">Все институты</option>{catalog.institutes.map(i => <option value={i.id} key={i.id}>{i.name}</option>)}</select><select aria-label="Курс" value={course} onChange={e => setCourse(e.target.value)}><option value="">Все курсы</option>{[1,2,3,4,5,6].map(c => <option key={c} value={c}>{c} курс</option>)}</select></div>}{modal === "search" && <div className="search-services">{navigation.filter(n => n.label.toLowerCase().includes(query.toLowerCase())).map(n => <button key={n.id} onClick={() => go(n.id)}><Icon name={n.icon}/>{n.label}<Icon name="arrow" size={16}/></button>)}{query.trim().length > 1 && groupData?.schedule?.flatMap(d => d.classes.map(l => ({...l, date:d.date}))).filter(l => `${l.subject} ${l.teacher}`.toLowerCase().includes(query.toLowerCase())).slice(0, 12).map((l, i) => <button key={`${l.id}-${i}`} onClick={() => { setDate(l.date); go("schedule"); setDetail(l) }}><Icon name="calendar"/><span>{l.subject}<small>{l.teacher} · {shortDate(l.date)}</small></span></button>)}</div>}<div className="result-label">{filteredGroups.length} групп{modal === "search" && " · преподаватели выбранной группы"}</div><div className="group-results">{filteredGroups.slice(0, 100).map(([id, g]) => <div className="group-result" key={id}><button onClick={() => chooseGroup(id)} disabled={!ready}><span className="group-initial">{id.slice(0,2)}</span><span><strong>{id}</strong><small>{g.institute} · {g.course || "—"} курс</small></span>{id === data.group ? <Icon name="check" size={18}/> : <Icon name="arrow" size={17}/>}</button><button className={`favorite ${data.favorites.includes(id) ? "active" : ""}`} aria-label={`${data.favorites.includes(id) ? "Убрать" : "Добавить"} ${id} в избранное`} onClick={() => update(d => ({ favorites: d.favorites.includes(id) ? d.favorites.filter(f => f !== id) : [...d.favorites, id] }))}>☆</button></div>)}{filteredGroups.length > 100 && <p className="footnote">Показаны первые 100 групп. Уточните поиск.</p>}{!filteredGroups.length && <Empty icon="search" title="Не удалось найти группу">Измените фильтр или откройте <a href={safeSource(catalog.meta.sourceUrl)} target="_blank" rel="noreferrer">расписание университета ↗</a>.</Empty>}</div></>}
      {modal === "task" && <form onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get("title") || "").trim(); if (!title) return; update(d => ({ tasks: [...d.tasks, { id: crypto.randomUUID(), title, date: String(f.get("date") || ""), kind: f.get("kind") === "homework" ? "homework" : "task", done: false }] })); setModal(null); setToast("Задача добавлена") }}><label className="field">Что нужно сделать?<input name="title" autoFocus required maxLength={300} placeholder="Например, подготовить доклад"/></label><div className="form-grid"><label className="field">Срок<input name="date" type="date"/></label><label className="field">Тип<select name="kind"><option value="task">Личное дело</option><option value="homework">Домашнее задание</option></select></label></div><p className="footnote">Запись хранится на этом устройстве и доступна без интернета.</p><button className="button primary wide" disabled={!ready}>Добавить задачу <Icon name="plus" size={17}/></button></form>}
      {modal === "plan" && <form onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get("title") || "").trim(); const start = String(f.get("start")); const end = String(f.get("end")); if (!title || end <= start) { setToast("Укажите окончание позже начала"); return } const next: Plan = { id: editPlan?.id || crypto.randomUUID(), title, date: String(f.get("date")), start, end, room: String(f.get("room") || ""), cancelled: f.get("cancelled") === "on" }; update(d => ({ plans: [...d.plans.filter(p => p.id !== next.id), next] })); setModal(null); setToast("Личный план сохранён") }}><label className="field">Название<input autoFocus name="title" required maxLength={300} defaultValue={editPlan?.title} placeholder="Встреча, подготовка или перенос пары"/></label><label className="field">Дата<input type="date" name="date" required defaultValue={editPlan?.date || date}/></label><div className="form-grid"><label className="field">Начало<input name="start" type="time" required defaultValue={editPlan?.start || "09:00"}/></label><label className="field">Окончание<input name="end" type="time" required defaultValue={editPlan?.end || "10:00"}/></label></div><label className="field">Место<input name="room" maxLength={200} defaultValue={editPlan?.room} placeholder="Корпус, аудитория или ссылка"/></label><label className="checkbox-field"><input type="checkbox" name="cancelled" defaultChecked={editPlan?.cancelled}/>Отметить как отменённое</label><p className="footnote">Личная запись. Официальное расписание группы не изменится.</p><div className="form-grid"><button className="button primary" disabled={!ready}>Сохранить</button>{editPlan && <button className="button" type="button" onClick={() => { update(d => ({ plans: d.plans.filter(p => p.id !== editPlan.id) })); setModal(null); setToast("Личная запись удалена") }}>Удалить запись</button>}</div></form>}
      {modal === "settings" && <><label className="field">Как тебя зовут?<input value={data.name} maxLength={40} placeholder="Имя (по желанию)" disabled={!ready} onChange={e => update({ name: e.target.value })}/></label><button className="settings-row" onClick={() => setLight(!light)} role="switch" aria-checked={light}><Icon name="sun"/><span>Светлая тема</span><span className={`switch ${light ? "on" : ""}`}/></button><button className="settings-row" onClick={openGroup}><Icon name="person"/><span>Моя группа</span><small>{data.group || "Не выбрана"}</small><Icon name="right" size={17}/></button><button className="settings-row" onClick={() => { void downloadText("tim-personal-backup.json", JSON.stringify({ version: 4, exportedAt: new Date().toISOString(), data }, null, 2)).then(() => setToast("Резервная копия подготовлена")).catch(() => setToast("Экспорт не завершён. Повторите сохранение файла.")) }}><Icon name="download"/><span>Скачать мои данные</span><Icon name="diagonal" size={17}/></button><BackupRestore current={data} ready={ready} onDone={() => setToast("Данные из копии добавлены")}/><div className="privacy-note"><Icon name="shield" size={24}/><h3>Твоё остаётся твоим.</h3><p>Имя, заметки и личные планы хранятся на этом устройстве. Учётная запись не нужна. Очистка данных приложения удаляет записи — сохраните резервную копию.</p></div><p className="footnote">ТИМ Кампус 4.0 · Независимый студенческий проект.<br/>Не является официальным приложением университета.</p></>}
      {modal === "sources" && <><div className="source-status"><span className="status-dot"/><strong>{sourceState()}</strong><button className="icon-button" disabled={syncing} aria-label="Проверить обновления данных" onClick={refresh}><Icon name="refresh"/></button></div>{syncError && <p className="notice">{syncError}</p>}<p className="muted">Расписание поступает из открытых источников РГАУ-МСХА. При расхождении ориентируйтесь на опубликованное вузом расписание.</p><div className="source-stats"><div><strong>{catalog.meta.totalGroups.toLocaleString("ru-RU")}</strong><span>групп в каталоге</span></div><div><strong>{catalog.meta.totalClasses.toLocaleString("ru-RU")}</strong><span>занятий в снимке</span></div></div>{checked && <p className="footnote">Проверка первоисточника: {new Date(checked).toLocaleString("ru-RU", { timeZone: "Europe/Moscow" })} МСК{scheduleWindow && <><br/>Период: {shortDate(scheduleWindow.from)} — {shortDate(scheduleWindow.to)}</>}</p>}<a className="source-link" href={safeSource(catalog.meta.sourceUrl)} target="_blank" rel="noreferrer"><Icon name="link"/><span>Документы расписания<small>timacad.ru</small></span><Icon name="diagonal"/></a><a className="source-link" href={safeSource(catalog.meta.electronicSourceUrl || "https://eg.timacad.ru/schedule/groups/")} target="_blank" rel="noreferrer"><Icon name="calendar"/><span>Электронное расписание<small>eg.timacad.ru</small></span><Icon name="diagonal"/></a><p className="footnote">Храним каталог и расписания последних трёх открытых групп. Проверяем обновления при запуске, восстановлении сети и каждый час, пока приложение открыто.</p><details><summary>Документы институтов</summary>{catalog.documents?.map((d, i) => <a className="document-row" key={i} href={safeSource(d.url)} target="_blank" rel="noreferrer">{d.title}<Icon name="diagonal" size={15}/></a>)}</details></>}
      {modal === "integration" && <><div className="integration-art"><Icon name="grid" size={42}/></div><h3>Идея сохранена. Доступ пока не подключён.</h3><p className="muted">{integration.includes("старосты") ? "Совместные переносы и отмены требуют входа, проверки полномочий старосты и подтверждений реальных участников группы. Сейчас можно вести личные изменения в разделе «Мои дела»." : integration.includes("Wallet") ? "Цифровой пропуск требует подключения системы доступа университета и официально подписанных карточек. Приложение не создаёт действующие пропуска." : integration.includes("аудитории") ? "Нужны полный реестр помещений и подтверждённая занятость. Мы не показываем кабинет свободным на основании неполного расписания." : integration.includes("виджеты") ? "Нативные виджеты и Live Activities требуют системных расширений для каждой платформы. В этом релизе доступен экран расписания." : "Для сторонних сервисов нужны проверка издателей, изолированное исполнение и разрешения. Сейчас доступны прямые ссылки на сервисы университета."}</p><button className="button primary" onClick={() => go(integration.includes("старосты") ? "planner" : "services")}>Понятно <Icon name="check" size={17}/></button></>}
    </ModalFrame>}
    {detail && <ModalFrame title={detail.subject} onClose={() => setDetail(null)}><div className="lesson-details"><p><Icon name="calendar"/>{shortDate(date)}</p><p><Icon name="clock"/>{detail.start}–{detail.end} · МСК</p><p><Icon name="person"/>{detail.teacher || "Преподаватель не указан"}</p><p><Icon name="pin"/>{[detail.building, detail.room && `ауд. ${detail.room}`].filter(Boolean).join(" · ") || "Место не указано"}</p></div><a className="button wide" href={safeSource(detail.sourceUrl || groupData?.sourceUrl)} target="_blank" rel="noreferrer">Проверить в первоисточнике <Icon name="diagonal" size={16}/></a><button className="button primary wide" onClick={() => { const l = detail; setDetail(null); openPlan({ id: crypto.randomUUID(), title: l.subject, date, start: l.start, end: l.end, room: [l.building, l.room].filter(Boolean).join(", ") }) }}>Добавить личное изменение <Icon name="plus" size={16}/></button><p className="footnote">Перенос или отмена будут личной записью на этом устройстве.</p></ModalFrame>}
    {toast && <div className="toast" role="status"><Icon name="check" size={18}/>{toast}</div>}
  </div>
}
